// ==================== SERVICES ====================
export const services = [
  {
    id: "web-development",
    icon: "💻",
    color: "accent",
    coverImage: "https://images.unsplash.com/photo-1555066931-4365d14bab8c?auto=format&fit=crop&w=800&q=80",
    name: "Web & App Development",
    short: "Custom websites, web apps & mobile applications",
    desc: "We build scalable, high-performance digital products using modern stacks. From landing pages to full SaaS platforms.",
    features: [
      "React / Next.js / Vue.js frontend",
      "Node.js, Python, Laravel backend",
      "Flutter & React Native mobile apps",
      "E-commerce & SaaS platforms",
      "Custom CMS & admin dashboards",
      "REST & GraphQL APIs",
    ],
    deliverables: ["Source code", "Documentation", "Deployment", "30-day support"],
    timeline: "2–8 weeks",
    slug: "web-development",
  },
  {
    id: "brand-design",
    icon: "🎨",
    color: "purple",
    coverImage: "https://images.unsplash.com/photo-1561070791-2526d30994b5?auto=format&fit=crop&w=800&q=80",
    name: "Brand & UI/UX Design",
    short: "Identity design that makes you unforgettable",
    desc: "We create brand identities and user interfaces that convert visitors into customers and build lasting recognition.",
    features: [
      "Logo & brand identity systems",
      "UI/UX wireframing & prototyping",
      "Figma design systems",
      "Conversion-optimized landing pages",
      "Motion & micro-interaction design",
      "Design-to-code handoff",
    ],
    deliverables: ["Brand kit", "Figma files", "Style guide", "Web assets"],
    timeline: "1–3 weeks",
    slug: "brand-design",
  },
  {
    id: "seo-geo",
    icon: "🔍",
    color: "accent",
    coverImage: "https://images.unsplash.com/photo-1432888498266-38ffec3eaf0a?auto=format&fit=crop&w=800&q=80",
    name: "SEO & GEO Optimization",
    short: "Rank on Google and AI-powered search engines",
    desc: "Future-proof your visibility. We optimize for traditional search engines and the new AI-powered search landscape.",
    features: [
      "Technical SEO audits & fixes",
      "GEO (AI Search Optimization)",
      "Local SEO for Nepal businesses",
      "On-page & off-page optimization",
      "Link building & authority growth",
      "Schema markup & structured data",
    ],
    deliverables: ["SEO audit", "Monthly reports", "Keyword rankings", "Traffic growth"],
    timeline: "Ongoing",
    slug: "seo-geo",
  },
  {
    id: "ads-campaigns",
    icon: "🎯",
    color: "orange",
    coverImage: "https://images.unsplash.com/photo-1611162617213-7d7a39e9b1d7?auto=format&fit=crop&w=800&q=80",
    name: "Ads Campaign Management",
    short: "Profitable paid advertising across all channels",
    desc: "We plan, launch, and optimize ad campaigns that deliver measurable ROI — not just clicks.",
    features: [
      "Meta (Facebook & Instagram) Ads",
      "Google Search & Display Ads",
      "TikTok & YouTube Ads",
      "Retargeting & funnel strategy",
      "A/B testing & creative optimization",
      "Weekly reporting & insights",
    ],
    deliverables: ["Campaign setup", "Ad creatives", "Weekly reports", "ROAS tracking"],
    timeline: "Ongoing",
    slug: "ads-campaigns",
  },
  {
    id: "content-creation",
    icon: "✍️",
    color: "pink",
    coverImage: "https://images.unsplash.com/photo-1542744173-8e7e53415bb0?auto=format&fit=crop&w=800&q=80",
    name: "Content Creation",
    short: "Content that builds authority and drives growth",
    desc: "Videos, blogs, social media, email campaigns — we create content that ranks, engages, and converts.",
    features: [
      "Short-form video & Instagram reels",
      "Blog & SEO article writing",
      "Social media management",
      "Email & newsletter campaigns",
      "YouTube content strategy",
      "Copywriting & brand voice",
    ],
    deliverables: ["Content calendar", "8–20 pieces/mo", "Analytics report", "Engagement growth"],
    timeline: "Ongoing",
    slug: "content-creation",
  },
  {
    id: "ai-automation",
    icon: "🤖",
    color: "cyan",
    coverImage: "https://images.unsplash.com/photo-1677442135703-1787eea5ce01?auto=format&fit=crop&w=800&q=80",
    name: "AI Integration & Automation",
    short: "Automate operations with AI-powered tools",
    desc: "Integrate AI chatbots, automate workflows, and implement AI tools that save hours daily and scale your operations.",
    features: [
      "Custom AI chatbot integration",
      "CRM & workflow automation",
      "AI-powered analytics & insights",
      "Custom GPT & AI tool development",
      "Process automation (Zapier, n8n)",
      "API integrations & webhooks",
    ],
    deliverables: ["Working automations", "Documentation", "Training", "Ongoing support"],
    timeline: "1–4 weeks",
    slug: "ai-automation",
  },
];

// ==================== CASE STUDIES ====================
export const caseStudies = [
  {
    slug: "treknpal-seo-growth",
    client: "TrekNepal",
    industry: "Tourism & Travel",
    service: "SEO & GEO",
    color: "accent",
    emoji: "🏔️",
    title: "340% SEO Traffic Increase in 5 Months",
    summary: "How we took TrekNepal from invisible to page one for 50+ high-value tourism keywords.",
    challenge: "TrekNepal had a beautiful website but zero search presence. Competitors dominated every valuable keyword.",
    solution: "Complete technical SEO overhaul, 40+ long-form content pieces, GEO optimization for AI search, and a link building campaign targeting tourism publications.",
    results: [
      { metric: "Organic Traffic", value: "+340%", period: "5 months" },
      { metric: "Keywords Ranking", value: "50+", period: "Page 1" },
      { metric: "Leads Generated", value: "+180%", period: "Monthly" },
      { metric: "Revenue Impact", value: "+$24K", period: "Attributable" },
    ],
    tags: ["SEO", "GEO", "Content", "Link Building"],
    featured: true,
    image: "/case-studies/treknpal.jpg",
    coverImage: "https://images.unsplash.com/photo-1551632811-561732d1e306?auto=format&fit=crop&w=800&q=80",
  },
  {
    slug: "swastik-meta-ads",
    client: "Swastik Furniture",
    industry: "E-commerce / Retail",
    service: "Ads Campaign",
    color: "orange",
    emoji: "🪑",
    title: "4.2x ROAS on Meta Ads — From Loss to Profit",
    summary: "Completely rebuilt their Meta ads strategy and turned a money-burning campaign into a profit machine.",
    challenge: "Spending NPR 80K/month on Meta Ads with 0.8x ROAS. Ad fatigue, poor targeting, and generic creatives.",
    solution: "Full audit and restart: audience research, UGC-style creatives, retargeting funnels, and weekly optimization sprints.",
    results: [
      { metric: "ROAS", value: "4.2x", period: "Average" },
      { metric: "Cost Per Purchase", value: "-62%", period: "Reduction" },
      { metric: "Monthly Revenue", value: "+NPR 2.1L", period: "From ads" },
      { metric: "CTR", value: "+310%", period: "Improvement" },
    ],
    tags: ["Meta Ads", "Creative", "Strategy"],
    featured: true,
    image: "/case-studies/swastik.jpg",
    coverImage: "https://images.unsplash.com/photo-1555041469-a586c61ea9bc?auto=format&fit=crop&w=800&q=80",
  },
  {
    slug: "paysewa-saas-development",
    client: "PaySewa",
    industry: "Fintech / SaaS",
    service: "Web Development",
    color: "blue",
    emoji: "💳",
    title: "Full SaaS Platform Built in 8 Weeks",
    summary: "Designed and built a complete fintech SaaS platform from scratch — payments, dashboards, and APIs.",
    challenge: "The founder had a working prototype but needed a production-ready, scalable platform with a proper UI.",
    solution: "Next.js frontend, Node.js + PostgreSQL backend, Stripe integration, admin dashboard, and automated deployments on AWS.",
    results: [
      { metric: "Delivery", value: "8 weeks", period: "On time" },
      { metric: "Uptime", value: "99.9%", period: "Since launch" },
      { metric: "Users", value: "2,000+", period: "In 3 months" },
      { metric: "Lighthouse Score", value: "97", period: "Performance" },
    ],
    tags: ["Next.js", "Node.js", "AWS", "Fintech"],
    featured: false,
    image: "/case-studies/paysewa.jpg",
    coverImage: "https://images.unsplash.com/photo-1563013544-824ae1b704d3?auto=format&fit=crop&w=800&q=80",
  },
  {
    slug: "himalayan-kitchen-geo",
    client: "Himalayan Kitchen",
    industry: "Restaurants / Food",
    service: "SEO & GEO",
    color: "pink",
    emoji: "🍜",
    title: "Now Recommended by ChatGPT for 'Best Momo in Kathmandu'",
    summary: "GEO optimization that put this restaurant inside AI search answers — not just Google.",
    challenge: "Heavy competition from bigger restaurants. Needed visibility in both Google Maps and AI-powered search.",
    solution: "Google Business Profile overhaul, structured data implementation, GEO content strategy, and review acquisition system.",
    results: [
      { metric: "AI Search", value: "Featured", period: "ChatGPT & Perplexity" },
      { metric: "Google Maps", value: "Top 3", period: "Kathmandu momo" },
      { metric: "Walk-ins", value: "+55%", period: "Monthly" },
      { metric: "Reviews", value: "4.8★", period: "200+ reviews" },
    ],
    tags: ["GEO", "Local SEO", "Google Maps"],
    featured: false,
    image: "/case-studies/himalayan.jpg",
    coverImage: "https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?auto=format&fit=crop&w=800&q=80",
  },
];

// ==================== BLOG POSTS ====================
export const blogPosts = [
  {
    slug: "what-is-geo-ai-search-optimization",
    title: "What is GEO? The Complete Guide to AI Search Optimization in 2025",
    excerpt: "GEO (Generative Engine Optimization) is how you get your business cited by ChatGPT, Perplexity, and Google AI Overview. Here's everything you need to know.",
    category: "SEO & GEO",
    readTime: "8 min read",
    date: "2025-01-15",
    tags: ["GEO", "SEO", "AI Search", "ChatGPT"],
    featured: true,
    color: "accent",
    emoji: "🤖",
    coverImage: "https://images.unsplash.com/photo-1677442135703-1787eea5ce01?auto=format&fit=crop&w=800&q=80",
  },
  {
    slug: "meta-ads-roas-nepal-guide",
    title: "How to Achieve 4x+ ROAS on Meta Ads for Nepal Businesses",
    excerpt: "Most Nepal businesses waste 60–70% of their Meta ad budget. Here's the exact framework we use to achieve 4x+ ROAS consistently.",
    category: "Ads & Growth",
    readTime: "12 min read",
    date: "2025-01-10",
    tags: ["Meta Ads", "ROAS", "Digital Marketing", "Nepal"],
    featured: true,
    color: "orange",
    emoji: "🎯",
    coverImage: "https://images.unsplash.com/photo-1611162617213-7d7a39e9b1d7?auto=format&fit=crop&w=800&q=80",
  },
  {
    slug: "nextjs-vs-wordpress-2025",
    title: "Next.js vs WordPress in 2025: Which Should You Choose?",
    excerpt: "The debate is over — for serious businesses, the answer is clear. We break down performance, SEO, cost, and scalability.",
    category: "Web Development",
    readTime: "10 min read",
    date: "2025-01-05",
    tags: ["Next.js", "WordPress", "Web Development"],
    featured: false,
    color: "blue",
    emoji: "💻",
    coverImage: "https://images.unsplash.com/photo-1555066931-4365d14bab8c?auto=format&fit=crop&w=800&q=80",
  },
  {
    slug: "seo-nepal-complete-guide-2025",
    title: "SEO in Nepal: The Complete 2025 Guide for Local Businesses",
    excerpt: "Everything a Nepal business needs to rank on Google — from technical SEO to local citations and content strategy.",
    category: "SEO & GEO",
    readTime: "15 min read",
    date: "2024-12-28",
    tags: ["SEO", "Nepal", "Local SEO", "Google"],
    featured: false,
    color: "accent",
    emoji: "🔍",
    coverImage: "https://images.unsplash.com/photo-1432888498266-38ffec3eaf0a?auto=format&fit=crop&w=800&q=80",
  },
];

// ==================== JOBS ====================
export const jobs = [
  {
    id: 1,
    title: "Senior Full-Stack Developer",
    type: "Full-time",
    location: "Kathmandu / Remote",
    department: "Engineering",
    salary: "NPR 80K – 1.5L",
    desc: "We're looking for a senior developer who can architect and build complex web applications end-to-end.",
    requirements: ["3+ years React/Next.js", "Node.js + PostgreSQL", "Cloud deployment (AWS/Vercel)", "Strong TypeScript skills"],
    emoji: "💻",
    color: "blue",
    posted: "2025-01-12",
  },
  {
    id: 2,
    title: "SEO & GEO Specialist",
    type: "Full-time",
    location: "Kathmandu",
    department: "Marketing",
    salary: "NPR 50K – 90K",
    desc: "Deep SEO expertise required, with growing knowledge of GEO and AI search optimization strategies.",
    requirements: ["2+ years SEO experience", "Ahrefs / SEMrush proficiency", "Technical SEO knowledge", "Content strategy skills"],
    emoji: "🔍",
    color: "accent",
    posted: "2025-01-10",
  },
  {
    id: 3,
    title: "Paid Media Specialist",
    type: "Full-time",
    location: "Kathmandu",
    department: "Marketing",
    salary: "NPR 45K – 80K",
    desc: "Run and optimize Meta and Google Ads campaigns across multiple client accounts with a focus on ROAS.",
    requirements: ["Meta Ads certified", "Google Ads experience", "Analytics proficiency", "Budget management"],
    emoji: "🎯",
    color: "orange",
    posted: "2025-01-08",
  },
  {
    id: 4,
    title: "UI/UX Designer",
    type: "Full-time",
    location: "Kathmandu / Remote",
    department: "Design",
    salary: "NPR 40K – 75K",
    desc: "Design beautiful, conversion-focused interfaces for our client projects from brand identity to interactive prototypes.",
    requirements: ["Figma expert", "UI/UX portfolio required", "Motion design skills", "Brand design experience"],
    emoji: "🎨",
    color: "purple",
    posted: "2025-01-05",
  },
];

// ==================== TESTIMONIALS ====================
export const testimonials = [
  {
    name: "Rajesh Shrestha",
    role: "Founder, TrekNepal",
    text: "SAAN Digital Solutions didn't just build our website — they built our entire online business. SEO traffic tripled in 4 months. Incredible work.",
    stars: 5,
    color: "#6366F1",
    source: "Google Reviews",
    avatar: "R",
  },
  {
    name: "Sunita Maharjan",
    role: "CEO, Swastik Furniture",
    text: "Our Meta ads were burning money before SAAN Digital Solutions took over. Now we're getting 4x ROAS consistently. These people know their craft.",
    stars: 5,
    color: "#8B5CF6",
    source: "WhatsApp",
    avatar: "S",
  },
  {
    name: "Anish Karki",
    role: "CTO, PaySewa",
    text: "They built our entire SaaS platform from scratch and launched it on time. The code quality is exceptional. Highly recommend.",
    stars: 5,
    color: "#3B82F6",
    source: "LinkedIn",
    avatar: "A",
  },
  {
    name: "Priya Tamang",
    role: "Owner, Himalayan Kitchen",
    text: "Our restaurant now shows up when people ask ChatGPT for the best momo in Kathmandu. GEO is the future and SAAN Digital Solutions gets it.",
    stars: 5,
    color: "#F97316",
    source: "Google Reviews",
    avatar: "P",
  },
  {
    name: "Binita Rai",
    role: "Founder, Binita's Boutique",
    text: "The content strategy helped us grow to 50K Instagram followers in 8 months. Pure quality and consistency.",
    stars: 5,
    color: "#EC4899",
    source: "Instagram",
    avatar: "B",
  },
  {
    name: "Dev Adhikari",
    role: "GM, Pokhara View Hotel",
    text: "They digitised our entire hotel booking system. Revenue up 60% in six months. Best investment we've made.",
    stars: 5,
    color: "#22D3EE",
    source: "Google Reviews",
    avatar: "D",
  },
];

// ==================== STATS ====================
export const stats = [
  { num: 10, suffix: "+", label: "Projects Delivered", sub: "Across 12+ industries" },
  { num: 98, suffix: "%", label: "Client Retention", sub: "Satisfaction rate" },
  { num: 5, suffix: "+", label: "Years of Excellence", sub: "In digital growth" },
  { num: 3, suffix: "+", label: "Countries Served", sub: "Nepal & worldwide" },
];

// ==================== PRICING ====================
export const plans = [
  {
    name: "Starter",
    desc: "For small businesses needing their digital foundation built and optimised.",
    price: "NPR 25K",
    period: "/mo",
    from: true,
    featured: false,
    features: [
      { text: "Professional website (up to 8 pages)", included: true },
      { text: "Basic SEO setup & optimisation", included: true },
      { text: "Google Business Profile setup", included: true },
      { text: "Monthly analytics report", included: true },
      { text: "WhatsApp support", included: true },
      { text: "Ads campaign management", included: false },
      { text: "Content creation", included: false },
    ],
    cta: "Get Started",
    ctaStyle: "outline",
  },
  {
    name: "Growth",
    desc: "Full development + marketing for businesses ready to scale aggressively.",
    price: "NPR 75K",
    period: "/mo",
    from: true,
    featured: true,
    badge: "Most Popular",
    features: [
      { text: "Custom web app or landing pages", included: true },
      { text: "Advanced SEO + GEO optimisation", included: true },
      { text: "Meta + Google Ads management", included: true },
      { text: "8 pieces of content per month", included: true },
      { text: "Social media management", included: true },
      { text: "Bi-weekly performance reviews", included: true },
      { text: "Dedicated account manager", included: true },
    ],
    cta: "Start Growing",
    ctaStyle: "filled",
  },
  {
    name: "Enterprise",
    desc: "End-to-end development and marketing at scale for established businesses.",
    price: "Custom",
    period: "",
    from: false,
    featured: false,
    features: [
      { text: "Full custom software development", included: true },
      { text: "Unlimited SEO, GEO & content", included: true },
      { text: "All paid media channels", included: true },
      { text: "AI automation & chatbot integration", included: true },
      { text: "Custom analytics dashboard", included: true },
      { text: "Weekly strategy calls", included: true },
      { text: "Priority 24/7 support", included: true },
    ],
    cta: "Book a Call",
    ctaStyle: "outline",
  },
];
